const MAPEAMENTOS_APIS = {
  PRODUTO: {
    url: 'mc-cadastro-ms/api/v1/produto',
    urlBusca: 'mc-cadastro-ms/api/v1/produto/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/produto/',
    urlListAll: 'mc-cadastro-ms/api/v1/produto/listAll',
    nomeArquivo: 'Produtos/1 - Produtos.json',
    nivelDependencia: 3,
    contentBusca: ['descricao', 'classificacaoProduto.id'],
    dependencia: [
      { idSubstituido: 'subProduto.id', arquivoDependencia: 'Produtos/33 - SubProdutos.json'},
      { idSubstituido: 'classificacaoProduto.id', arquivoDependencia: 'Produtos/2 - Classificacoes.json'},
      { idSubstituido: 'grupoProduto.id', arquivoDependencia: 'Produtos/3 - GrupoProdutos.json'},
      { idSubstituido: 'focoNegocio.id', arquivoDependencia: 'Produtos/4 - FocosNegocio.json'},
      { idSubstituido: 'tipoProduto.id', arquivoDependencia: 'Produtos/5 - TiposProduto.json'},
      { idSubstituido: 'produtoIndexador.id', arquivoDependencia: 'Produtos/6 - ProdutosIndexadores.json'},
      { idSubstituido: 'produtoTPRecebimento.id', arquivoDependencia: 'Produtos/7 - TiposRecebimento.json'},
    ]
  },
  CLASSIFICACAO_PRODUTO: {
    url: 'mc-cadastro-ms/api/v1/classificacaoProduto',
    urlBusca: 'mc-cadastro-ms/api/v1/classificacaoProduto/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/classificacaoProduto/',
    nomeArquivo: 'Produtos/2 - Classificacoes.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/1 - Produtos.json',
    campoBusca: 'classificacaoProduto.id',
  },
  GRUPO_PRODUTO: {
    url: 'mc-cadastro-ms/api/v1/grupoProduto',
    urlBusca: 'mc-cadastro-ms/api/v1/grupoProduto/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/grupoProduto/',
    nomeArquivo: 'Produtos/3 - GrupoProdutos.json',
    nivelDependencia: 2,
    nomeArquivoReferencia: 'Produtos/1 - Produtos.json',
    campoBusca: 'grupoProduto.id',
    dependencia: [
      { idSubstituido: 'grupoProdutoRisco.id', arquivoDependencia: 'Produtos/9 - GruposProdutoRisco.json' },
    ],
  },
  SUB_PRODUTO: {
    url: 'mc-cadastro-ms/api/v1/subProduto',
    urlBusca: 'mc-cadastro-ms/api/v1/subProduto/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/subProduto/',
    nomeArquivo: 'Produtos/33 - SubProdutos.json',
    nivelDependencia: 2,
    nomeArquivoReferencia: 'Produtos/1 - Produtos.json',
    campoBusca: 'subProduto.id',
  },
  FOCO_NEGOCIO: {
    url: 'mc-cadastro-ms/api/v1/focoNegocio',
    urlBusca: 'mc-cadastro-ms/api/v1/focoNegocio/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/focoNegocio/',
    nomeArquivo: 'Produtos/4 - FocosNegocio.json',
    nivelDependencia: 2,
    nomeArquivoReferencia: 'Produtos/1 - Produtos.json',
    campoBusca: 'focoNegocio.id',
    dependencia: [
      { idSubstituido: 'segmentoTarifador.id', arquivoDependencia: 'Produtos/8 - SegmentosTarifadores.json' },
    ],
  },
  TIPO_PRODUTO: {
    url: 'mc-cadastro-ms/api/v1/tipoProduto',
    urlBusca: 'mc-cadastro-ms/api/v1/tipoProduto/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/tipoProduto/',
    nomeArquivo: 'Produtos/5 - TiposProduto.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/1 - Produtos.json',
    campoBusca: 'tipoProduto.id',
  },
  PRODUTO_INDEXADOR: {
    url: 'mc-cadastro-ms/api/v1/produtoIndexador',
    urlBusca: 'mc-cadastro-ms/api/v1/produtoIndexador/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/produtoIndexador/',
    nomeArquivo: 'Produtos/6 - ProdutosIndexadores.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/1 - Produtos.json',
    campoBusca: 'produtoIndexador.id',
  },
  TIPO_RECEBIMENTO: {
    url: 'mc-cadastro-ms/api/v1/produtoTPRecebimento',
    urlBusca: 'mc-cadastro-ms/api/v1/produtoTPRecebimento/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/produtoTPRecebimento/',
    nomeArquivo: 'Produtos/7 - TiposRecebimento.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/1 - Produtos.json',
    campoBusca: 'produtoTPRecebimento.id',
  },
  SEGMENTO_TARIFADOR: {
    url: 'mc-cadastro-ms/api/v1/segmentoTarifador',
    urlBusca: 'mc-cadastro-ms/api/v1/segmentoTarifador/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/segmentoTarifador/',
    nomeArquivo: 'Produtos/8 - SegmentosTarifadores.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/4 - FocosNegocio.json',
    campoBusca: 'segmentoTarifador.id',
  },
  GRUPO_PRODUTO_RISCO: {
    url: 'mc-cadastro-ms/api/v1/grupoProdutoRisco',
    urlBusca: 'mc-cadastro-ms/api/v1/grupoProdutoRisco/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/grupoProdutoRisco/',
    nomeArquivo: 'Produtos/9 - GruposProdutoRisco.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/3 - GrupoProdutos.json',
    campoBusca: 'grupoProdutoRisco.id',
  },
  PRODUTO_KIT: {
    urlBuscaId: 'mc-cadastro-ms/api/v1/produtoKit/findAllProdutoKitByProdutoId/',
    urlBusca: 'mc-cadastro-ms/api/v1/produtoKit/findAllProdutoKitByProdutoId/',
    url: 'mc-cadastro-ms/api/v1/produtoKit',
    nomeArquivo: 'Produtos/10 - ProdutosKit.json',
    nivelDependencia: 5,
    nomeArquivoReferencia: 'Produtos/1 - Produtos.json',
    campoBusca: 'id',
    contentBusca: ['produto.id', 'kitDocumento.id'],
    dependencia: [
      {idSubstituido: 'produto.id', arquivoDependencia: 'Produtos/1 - Produtos.json' },
      {idSubstituido: 'kitDocumento.id', arquivoDependencia: 'Produtos/23 - KitsDocumentos.json' },
    ],
  },
  PRODUTO_GARANTIA: {
    urlBuscaId: 'mc-cadastro-ms/api/v1/produtoGarantia/findAllProdutoGarantiaByProdutoId/',
    urlBusca: 'mc-cadastro-ms/api/v1/produtoGarantia/findAllProdutoGarantiaByProdutoId/',
    url: 'mc-cadastro-ms/api/v1/produtoGarantia',
    nomeArquivo: 'Produtos/11 - ProdutosGarantia.json',
    nivelDependencia: 5,
    nomeArquivoReferencia: 'Produtos/1 - Produtos.json',
    campoBusca: 'id',
    contentBusca: ['produto.id', 'garantiaCategoria.id'],
    dependencia: [
      {idSubstituido: 'produto.id', arquivoDependencia: 'Produtos/1 - Produtos.json' },
      {idSubstituido: 'garantiaCategoria.id', arquivoDependencia: 'Produtos/13 - GarantiasCategorias.json' },
    ],
  },
  PRODUTO_TARIFA: {
    urlBuscaId: 'mc-cadastro-ms/api/v1/produtoTarifa/findAllProdutoTarifaByProdutoId/',
    urlBusca: 'mc-cadastro-ms/api/v1/produtoTarifa/findAllProdutoTarifaByProdutoId/',
    url: 'mc-cadastro-ms/api/v1/produtoTarifa',
    nomeArquivo: 'Produtos/12 - ProdutosTarifa.json',
    nivelDependencia: 5,
    nomeArquivoReferencia: 'Produtos/1 - Produtos.json',
    campoBusca: 'id',
    contentBusca: ['produto.id', 'tarifa.id'],
    dependencia: [
      {idSubstituido: 'produto.id', arquivoDependencia: 'Produtos/1 - Produtos.json' },
      {idSubstituido: 'tarifa.id', arquivoDependencia: 'Produtos/18 - Tarifas.json' },
    ],
  },
  GARANTIA_CATEGORIA: {
    url: 'mc-cadastro-ms/api/v1/garantiaCategoria',
    urlBuscaId: 'mc-cadastro-ms/api/v1/garantiaCategoria/',
    urlBusca: 'mc-cadastro-ms/api/v1/garantiaCategoria/search/0?descricao=',
    nomeArquivo: 'Produtos/13 - GarantiasCategorias.json',
    nivelDependencia: 2,
    nomeArquivoReferencia: 'Produtos/11 - ProdutosGarantia.json',
    campoBusca: 'garantiaCategoria',
    contentBusca: ['descricao', 'ativo'],
    dependencia: [
      { idSubstituido: 'garantiaNivel.id', arquivoDependencia: 'Produtos/15 - NiveisGarantia.json' },
      { idSubstituido: 'idGarantiaClassificacao', arquivoDependencia: 'Produtos/16 - ClassificacoesGarantia.json' },
      { idSubstituido: 'tipoGarantia.id', arquivoDependencia: 'Produtos/14 - TiposGarantia.json' },
      { idSubstituido: 'grupoGarantia.id', arquivoDependencia: 'Produtos/17 - GruposGarantia.json' },
    ],
  },
  TIPO_GARANTIA: {
    url: 'mc-cadastro-ms/api/v1/garantiaTipo',
    urlBusca: 'mc-cadastro-ms/api/v1/garantiaTipo/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/garantiaTipo/',
    nomeArquivo: 'Produtos/14 - TiposGarantia.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/13 - GarantiasCategorias.json',
    campoBusca: 'tipoGarantia',
  },
  NIVEL_GARANTIA: {
    url: 'mc-cadastro-ms/api/v1/garantiaNivel',
    urlBusca: 'mc-cadastro-ms/api/v1/garantiaNivel/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/garantiaNivel/',
    nomeArquivo: 'Produtos/15 - NiveisGarantia.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/13 - GarantiasCategorias.json',
    campoBusca: 'garantiaNivel',
  },
  CLASSIFICACAO_GARANTIA: {
    url: 'mc-cadastro-ms/api/v1/garantiaClassificacao',
    urlBusca: 'mc-cadastro-ms/api/v1/garantiaClassificacao/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/garantiaClassificacao/',
    nomeArquivo: 'Produtos/16 - ClassificacoesGarantia.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/13 - GarantiasCategorias.json',
    campoBusca: 'idGarantiaClassificacao',
  },
  GRUPO_GARANTIA :{
    url: 'mc-cadastro-ms/api/v1/grupoGarantia',
    urlBusca: 'mc-cadastro-ms/api/v1/grupoGarantia/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/grupoGarantia/',
    nomeArquivo: 'Produtos/17 - GruposGarantia.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/13 - GarantiasCategorias.json',
    campoBusca: 'grupoGarantia',
  },
  TARIFA :{
    url: 'mc-cadastro-ms/api/v1/tarifa',
    urlBusca: 'mc-cadastro-ms/api/v1/tarifa/search/0?nomeTarifa=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/tarifa/',
    nomeArquivo: 'Produtos/18 - Tarifas.json',
    nivelDependencia: 4,
    nomeArquivoReferencia: 'Produtos/12 - ProdutosTarifa.json',
    campoBusca: 'tarifa',
    campoDescricao: 'nomeTarifa',
    contentBusca: ['nomeTarifa', 'codigoSubCategoria.id'],
    dependencia: [
      { idSubstituido: 'eventoTarifador.id', arquivoDependencia: 'Produtos/19 - Eventos.json' },
    ]
  },
  EVENTO :{
    url: 'mc-cadastro-ms/api/v1/evento',
    urlBusca: 'mc-cadastro-ms/api/v1/evento/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/evento/',
    nomeArquivo: 'Produtos/19 - Eventos.json',
    nivelDependencia: 3,
    nomeArquivoReferencia: 'Produtos/18 - Tarifas.json',
    campoBusca: 'entidadeTarifador',
    dependencia: [
      { idSubstituido: 'tipoEvento.id', arquivoDependencia: 'Produtos/20 - TiposEvento.json' },
      { idSubstituido: 'situacao.id', arquivoDependencia: 'Produtos/21 - Situacoes.json' }
    ]
  },
  TIPO_EVENTO :{
    url: 'mc-cadastro-ms/api/v1/tipoEvento',
    urlBusca: 'mc-cadastro-ms/api/v1/tipoEvento/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/tipoEvento/',
    nomeArquivo: 'Produtos/20 - TiposEvento.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/19 - Eventos.json',
    campoBusca: 'tipoEvento',
  },
  SITUACAO :{
    url: 'mc-cadastro-ms/api/v1/situacao',
    urlBusca: 'mc-cadastro-ms/api/v1/situacao/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/situacao/',
    nomeArquivo: 'Produtos/21 - Situacoes.json',
    nivelDependencia: 2,
    nomeArquivoReferencia: 'Produtos/19 - Eventos.json',
    campoBusca: 'situacao',
    //contentBusca: ['descricao', 'tipoSituacao.descricao'],
    dependencia: [
      { idSubstituido: 'tipoSituacao.id', arquivoDependencia: 'Produtos/22 - TipoSituacao.json' }
    ],
  },
  TIPO_SITUACAO: {
    url: 'mc-cadastro-ms/api/v1/tipoSituacao',
    urlBusca: 'mc-cadastro-ms/api/v1/tipoSituacao/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/tipoSituacao/',
    nomeArquivo: 'Produtos/22 - TipoSituacao.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/21 - Situacoes.json',
    campoBusca: 'tipoSituacao',
  },
  KIT_DOCUMENTO :{
    url: 'mc-cadastro-ms/api/v1/kitDocumentos',
    urlBusca: 'mc-cadastro-ms/api/v1/kitDocumentos/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/kitDocumentos/',
    nomeArquivo: 'Produtos/23 - KitsDocumentos.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/10 - ProdutosKit.json',
    campoBusca: 'kitDocumento',
  },
  MULTIFLOW: {
    parecer: 'mc-multiflow-ms/api/v1/ocorrencia/parecer?',
    avancar: 'mc-multiflow-ms/api/v1/esteira/finalizarEtapa',
    iniciarEsteira: 'mc-multiflow-ms/api/v1/esteira/iniciarEtapa?',
    method: 'POST'
  },
  GRUPOS_KEYCLOAK: {
    url: 'auth/admin/realms/multiplicacapital/groups?',
    urlBusca: 'auth/admin/realms/multiplicacapital/groups?search=',
  },
  SELECIONAR_CEDENTE: {
    url: 'mc-api-gateway-ms/v1/cedentes/search/0?numeroRegistros=100&nome=',
  }
};

export default MAPEAMENTOS_APIS;

/*
  DOCUMENTO_KIT: {
    urlBuscaId: 'mc-cadastro-ms/api/v1/documentoKit/findAllDocumentoKitByKitDocumentoId/',
    nomeArquivo: 'Produtos/24 - DocumentosKit.json',
    nivelDependencia: 5,
    nomeArquivoReferencia: 'Produtos/23 - KitsDocumentos.json',
    campoBusca: 'id',
    dependencia: [
      {idSubstituido: 'idDocumento', arquivoDependencia: 'Produtos/24 - MC_CAD_DOCUMENTO'},
      {idSubstituido: 'idKitDocumento', arquivoDependencia: 'Produtos/22 - MC_CAD_KIT_DOCUMENTO'},
    ],
  },
  DOCUMENTO :{
    url: 'mc-cadastro-ms/api/v1/documento',
    urlBusca: 'mc-cadastro-ms/api/v1/documento/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/documento/',
    nomeArquivo: 'Produtos/25 - Documentos.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/24 - DocumentosKit.json',
    campoBusca: 'documento',
    chavesIgnoradas: ['modeloContrato']
  },
  DOCUMENTO_CONSULTA :{
    urlBuscaId: 'mc-cadastro-ms/api/v1/documento-consulta/documento/',
    nomeArquivo: 'Produtos/26 - DocumentosConsulta.json',
    nivelDependencia: 2,
    nomeArquivoReferencia: 'Produtos/25 - Documentos.json',
    campoBusca: 'id',
    composicao: ['idDocumento', 'descricao'],
    dependencia: [{ idSubstituido: 'idDocumento', arquivoDependencia: 'Produtos/24 - MC_CAD_DOCUMENTO' }],
  },
  DOCUMENTO_PARTE :{
    urlBuscaId: 'mc-cadastro-ms/api/v1/documentoParte/findAllByDocumentoId/',
    nomeArquivo: 'Produtos/27 - DocumentoParte.json',
    nivelDependencia: 2,
    nomeArquivoReferencia: 'Produtos/25 - Documentos.json',
    campoBusca: 'id',
    dependencia: [
      {idSubstituido: 'idDocumento', arquivoDependencia: 'Produtos/24 - MC_CAD_DOCUMENTO'},
      {idSubstituido: 'idEntidade', arquivoDependencia: 'Produtos/31 - MC_CAD_ENTIDADE'},
    ],
  },
  DOCUMENTO_SECAO :{
    urlBuscaId: 'mc-cadastro-ms/api/v1/documentoSecao/findAllByDocumentoId/',
    nomeArquivo: 'Produtos/28 - DocumentosSecao.json',
    nivelDependencia: 2,
    nomeArquivoReferencia: 'Produtos/25 - Documentos.json',
    campoBusca: 'id',
    composicao: ['idDocumento', 'descricao'],
    dependencia: [
      { idSubstituido: 'idDocumento', arquivoDependencia: 'Produtos/24 - MC_CAD_DOCUMENTO' }
    ],
  },
  DOCUMENTO_CARTAO_ASSINATURA :{
    urlBuscaId: 'mc-cadastro-ms/api/v1/documentoCartaoAssinatura/findAllDocumentoCartaoAssinaturaByDocumentoId/',
    nomeArquivo: 'Produtos/29 - DocumentoCartaoAssinatura.json',
    nivelDependencia: 5,
    nomeArquivoReferencia: 'Produtos/25 - Documentos.json',
    campoBusca: 'id',
    {idSubstituido: 'idDocumento', arquivoDependencia: 'Produtos/24 - MC_CAD_DOCUMENTO'},
      {idSubstituido: 'idCartaoAssinatura', arquivoDependencia: 'Produtos/28 - MC_CAD_CARTAO_ASSINATURA'},
    ],
  },
  CARTAO_ASSINATURA :{
    url: 'mc-cadastro-ms/api/v1/cartaoAssinatura',
    urlBusca: 'mc-cadastro-ms/api/v1/cartaoAssinatura/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/cartaoAssinatura/',
    nomeArquivo: 'Produtos/30 - CartaoAssinatura.json',
    nivelDependencia: 2,
    nomeArquivoReferencia: 'Produtos/29 - DocumentoCartaoAssinatura.json',
    campoBusca: 'idCartaoAssinatura',
    composicao: ['nome', 'cpf'],
    dependencia: [
      { idSubstituido: 'idTituloAssinatura', arquivoDependencia: 'Produtos/29 - MC_CAD_TITULO_ASSINATURA' }
    ],
  },
  TITULO_ASSINATURA :{
    url: 'mc-cadastro-ms/api/v1/tituloAssinatura',
    urlBusca: 'mc-cadastro-ms/api/v1/tituloAssinatura/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/tituloAssinatura/',
    nomeArquivo: 'Produtos/31 - TituloAssinatura.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/30 - CartaoAssinatura.json',
    campoBusca: 'tituloAssinatura',
  },
  ENTIDADE: {
    url: 'mc-cadastro-ms/api/v1/entidade',
    urlBusca: 'mc-cadastro-ms/api/v1/entidade/search/0?descricao=',
    urlBuscaId: 'mc-cadastro-ms/api/v1/entidade/',
    nomeArquivo: 'Produtos/32 - Entidades.json',
    nivelDependencia: 1,
    nomeArquivoReferencia: 'Produtos/27 - DocumentoParte.json',
    campoBusca: 'idEntidade',
  },*/