const MAPEAMENTO_ESTEIRAS = {
    ESTEIRAS: {
        urlListAll: 'mc-multiflow-ms/api/v1/modeloesteira/all',
        urlBusca: 'mc-multiflow-ms/api/v1/modeloesteira/pesquisar?status=TODOS&nome=',
        nomeArquivo: 'Esteiras/1 - esteiras.json',
        nivelDependencia: 6,
        campoDescricao: 'nome',
    },
    ESTEIRA_VINCULADA: {
        urlBuscaId: 'mc-multiflow-ms/api/v1/modeloesteira/pesquisarporid/',
        urlBusca: 'mc-multiflow-ms/api/v1/modeloesteira/pesquisar?status=TODOS&nome=',
        nomeArquivo: 'Esteiras/2 - esteirasVinculadas.json',
        nivelDependencia: 5,
        campoDescricao: 'nome',
        nomeArquivoReferencia: 'Esteiras/1 - esteiras.json',
        campoBusca: 'idModeloEsteiraVinculado',
    },
    TIPOESTEIRAS: {
        urlBuscaId: 'mc-multiflow-ms/api/v1/tipoesteira/pesquisarporid/',
        urlBusca: 'mc-multiflow-ms/api/v1/tipoesteira/pesquisar?status=TODOS&nome=',
        nomeArquivo: 'Esteiras/3 - tipoEsteiras.json',
        nivelDependencia: 1,
        campoDescricao: 'nome',
        nomeArquivoReferencia: 'Esteiras/1 - esteiras.json',
        campoBusca: 'tipoEsteira.id',
    },
    ETAPAS: {
        urlBuscaId: 'mc-multiflow-ms/api/v1/modeloetapa/pesquisarporid/',
        urlBusca: 'mc-multiflow-ms/api/v1/modeloetapa/pesquisar?status=TODOS&nome=',
        nomeArquivo: 'Esteiras/4 - etapas.json',
        nivelDependencia: 4,
        campoDescricao: 'nome',
        nomeArquivoReferencia: 'Esteiras/1 - esteiras.json',
        campoBusca: 'modeloEtapas.modeloEtapa.id',
    },
    SUB_ETAPAS: {
        urlBuscaId: 'mc-multiflow-ms/api/v1/modelosubetapa/pesquisarporid/',
        urlBusca: 'mc-multiflow-ms/api/v1/modelosubetapa/pesquisar?status=TODOS&nome=',
        nomeArquivo: 'Esteiras/5 - subetapas.json',
        nivelDependencia: 3,
        campoDescricao: 'nome',
        nomeArquivoReferencia: 'Esteiras/4 - etapas.json',
        campoBusca: 'modeloSubEtapaModel.modeloSubEtapa.id',
    },
    ACOES: {
        urlBuscaId: 'mc-multiflow-ms/api/v1/modeloacao/pesquisarporid/',
        urlBusca: 'mc-multiflow-ms/api/v1/modeloacao/pesquisar?status=TODOS&nome=',
        nomeArquivo: 'Esteiras/6 - acoes.json',
        nivelDependencia: 1,
        campoDescricao: 'nome',
        nomeArquivoReferencia: 'Esteiras/5 - subetapas.json',
        campoBusca: 'modeloAcao',
    },
    MOTIVOS_RETORNO: {
        urlBuscaId: 'mc-multiflow-ms/api/v1/motivo-retorno-esteira/pesquisarporid/',
        urlBusca: 'mc-multiflow-ms/api/v1/motivo-retorno-esteira/pesquisar?status=TODOS&nome=',
        nomeArquivo: 'Esteiras/7 - motivosRetorno.json',
        nivelDependencia: 1,
        campoDescricao: 'nome',
        nomeArquivoReferencia: 'Esteiras/5 - subetapas.json',
        campoBusca: 'motivosRetornoEsteira.id',
    },
    OPERADORES: {
        urlBuscaId: 'N/A',
        urlBusca: 'auth/admin/realms/multiplicacapital/groups?max=11&search=',
        nomeArquivo: 'Esteiras/8 - gruposKeycloak.json',
        nivelDependencia: 2,
        campoDescricao: 'grupo',
        nomeArquivoReferencia: 'Esteiras/5 - subetapas.json',
        campoBusca: 'operadores',
        env: 'keycloak',
    },
    OBSERVADORES: {
        urlBuscaId: 'N/A',
        urlBusca: 'auth/admin/realms/multiplicacapital/groups?max=11&search=',
        nomeArquivo: 'Esteiras/8 - gruposKeycloak.json',
        nivelDependencia: 2,
        campoDescricao: 'grupo',
        nomeArquivoReferencia: 'Esteiras/1 - esteiras.json',
        campoBusca: 'observadores',
        env: 'keycloak',
        adiciona: true
    },
    GESTORES: {
        urlBuscaId: 'N/A',
        urlBusca: 'auth/admin/realms/multiplicacapital/groups?max=11&search=',
        nomeArquivo: 'Esteiras/8 - gruposKeycloak.json',
        nivelDependencia: 2,
        campoDescricao: 'grupo',
        nomeArquivoReferencia: 'Esteiras/1 - esteiras.json',
        campoBusca: 'gestores',
        env: 'keycloak',
        adiciona: true
    },
    CONDICOES: {
        urlBuscaId: 'N/A/',
        nomeArquivo: 'Esteiras/9 - condicoes.json',
        nivelDependencia: 7,
        nomeArquivoReferencia: 'Esteiras/1 - esteiras.json',
        campoBusca: 'modeloEtapas.modeloEtapa.condicoes',
    },
};

export default MAPEAMENTO_ESTEIRAS;