const MAPEAMENTO_ESTEIRAS = {
  ESTEIRAS: {
    urlListAll: 'mc-multiflow-ms/api/v1/modeloesteira/all',
    urlBusca: 'mc-multiflow-ms/api/v1/modeloesteira/pesquisar?status=TODOS&nome=',
    url: 'mc-multiflow-ms/api/v1/modeloesteira',
    nomeArquivo: 'Esteiras/1 - esteiras.json',
    nivelDependencia: 5,
    campoDescricao: 'nome',
    method: 'patch',
  },
  ESTEIRA_VINCULADA: {
    urlBuscaId: 'mc-multiflow-ms/api/v1/modeloesteira/pesquisarporid/',
    urlBusca: 'mc-multiflow-ms/api/v1/modeloesteira/pesquisar?status=TODOS&nome=',
    url: 'mc-multiflow-ms/api/v1/modeloesteira',
    nomeArquivo: 'Esteiras/2 - esteirasVinculadas.json',
    nivelDependencia: 4,
    campoDescricao: 'nome',
    nomeArquivoReferencia: 'Esteiras/1 - esteiras.json',
    campoBusca: 'idModeloEsteiraVinculado',
    method: 'patch',
  },
  TIPOESTEIRAS: {
    urlBuscaId: 'mc-multiflow-ms/api/v1/tipoesteira/pesquisarporid/',
    urlBusca: 'mc-multiflow-ms/api/v1/tipoesteira/pesquisar?status=TODOS&nome=',
    url: 'mc-multiflow-ms/api/v1/tipoesteira',
    nomeArquivo: 'Esteiras/3 - tipoEsteiras.json',
    nivelDependencia: 1,
    campoDescricao: 'nome',
    nomeArquivoReferencia: 'Esteiras/1 - esteiras.json',
    campoBusca: 'tipoEsteira.id',
  },
  ETAPAS: {
    urlBuscaId: 'mc-multiflow-ms/api/v1/modeloetapa/pesquisarporid/',
    urlBusca: 'mc-multiflow-ms/api/v1/modeloetapa/pesquisar?status=TODOS&nome=',
    url: 'mc-multiflow-ms/api/v1/modeloetapa',
    nomeArquivo: 'Esteiras/4 - etapas.json',
    nivelDependencia: 3,
    campoDescricao: 'nome',
    nomeArquivoReferencia: 'Esteiras/1 - esteiras.json',
    campoBusca: 'modeloEtapas.modeloEtapa.id',
    dependencia: [
      { idSubstituido: 'modeloSubEtapaModel.modeloSubEtapa.id', arquivoDependencia: 'Esteiras/5 - subetapas.json' },
    ]
  },
  SUB_ETAPAS: {
    urlBuscaId: 'mc-multiflow-ms/api/v1/modelosubetapa/pesquisarporid/',
    urlBusca: 'mc-multiflow-ms/api/v1/modelosubetapa/pesquisar?status=TODOS&nome=',
    url: 'mc-multiflow-ms/api/v1/modelosubetapa',
    nomeArquivo: 'Esteiras/5 - subetapas.json',
    nivelDependencia: 2,
    campoDescricao: 'nome',
    nomeArquivoReferencia: 'Esteiras/4 - etapas.json',
    campoBusca: 'modeloSubEtapaModel.modeloSubEtapa.id',
    methodAtualizacao: 'patch',
    dependencia: [
      { idSubstituido: 'modeloAcao.id', arquivoDependencia: 'Esteiras/6 - acoes.json' },
      { idSubstituido: 'motivosRetornoEsteira.id', arquivoDependencia: 'Esteiras/7 - motivosRetorno.json' },
    ]
  },
  ACOES: {
    urlBuscaId: 'mc-multiflow-ms/api/v1/modeloacao/pesquisarporid/',
    urlBusca: 'mc-multiflow-ms/api/v1/modeloacao/pesquisar?status=TODOS&nome=',
    url: 'mc-multiflow-ms/api/v1/modeloacao',
    nomeArquivo: 'Esteiras/6 - acoes.json',
    nivelDependencia: 1,
    campoDescricao: 'nome',
    nomeArquivoReferencia: 'Esteiras/5 - subetapas.json',
    campoBusca: 'modeloAcao',
  },
  MOTIVOS_RETORNO: {
    urlBuscaId: 'mc-multiflow-ms/api/v1/motivo-retorno-esteira/pesquisarporid/',
    urlBusca: 'mc-multiflow-ms/api/v1/motivo-retorno-esteira/pesquisar?status=TODOS&nome=',
    url: 'mc-multiflow-ms/api/v1/motivo-retorno-esteira',
    nomeArquivo: 'Esteiras/7 - motivosRetorno.json',
    nivelDependencia: 1,
    campoDescricao: 'nome',
    nomeArquivoReferencia: 'Esteiras/5 - subetapas.json',
    campoBusca: 'motivosRetornoEsteira.id',
  },
  OPERADORES: {
    urlBuscaId: 'N/A',
    urlBusca: 'mc-keycloak-ms/api/v1/group/multiplicacapital',
    url: 'auth/admin/realms/multiplicacapital/groups',
    nomeArquivo: 'Esteiras/8 - gruposKeycloak.json',
    nivelDependencia: 1,
    campoDescricao: 'grupo',
    nomeArquivoReferencia: 'Esteiras/5 - subetapas.json',
    campoBusca: 'operadores',
    env: 'keycloak',
  },
  OBSERVADORES: {
    urlBuscaId: 'N/A',
    urlBusca: 'mc-keycloak-ms/api/v1/group/multiplicacapital',
    url: 'auth/admin/realms/multiplicacapital/groups',
    nomeArquivo: 'Esteiras/8 - gruposKeycloak.json',
    nivelDependencia: 1,
    campoDescricao: 'grupo',
    nomeArquivoReferencia: 'Esteiras/1 - esteiras.json',
    campoBusca: 'observadores',
    adiciona: true,
    env: 'keycloak',
  },
  GESTORES: {
    urlBuscaId: 'N/A',
    urlBusca: 'mc-keycloak-ms/api/v1/group/multiplicacapital',
    url: 'auth/admin/realms/multiplicacapital/groups',
    nomeArquivo: 'Esteiras/8 - gruposKeycloak.json',
    nivelDependencia: 1,
    campoDescricao: 'grupo',
    nomeArquivoReferencia: 'Esteiras/1 - esteiras.json',
    campoBusca: 'gestores',
    adiciona: true,
    env: 'keycloak',
  },
};

export default MAPEAMENTO_ESTEIRAS;